# Generated by Django 4.1.2 on 2022-10-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
