# Generated by Django 4.1.2 on 2022-10-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_remove_geeksmodel_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='title',
        ),
    ]
