# Generated by Django 4.1.2 on 2022-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_remove_geeksmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
